site_name: Unidad 1 - Tarea RA1
site_author: Manuel Andrades Pavia
site_description: Documentación de la práctica de Puesta en producción segura
site_url: https://andradesdev.github.io/Unidad1-TareaRA1-Andrades_Pavia_Manuel/

docs_dir: doc
site_dir: site

theme:
  name: material
  language: es

nav:
  - Inicio: index.md
  - Elementos de Python: elementos_python.md
  - Ejecución y Depuración: ejecucion_y_depuracion.md
  - Pruebas: pruebas.md
  - Ejecución en Sandbox: sandbox.md
  - Reflexión sobre Seguridad: reflexion.md
